#!/bin/bash

export GOPRIVATE=*gitlab.com/ciorg/*
export HOST_IP=localhost
export PORT=:8090
export PATH=~/go/bin:~/bin:$PATH
export PATH="~/.scripts:$PATH"
export PATH="$PATH:/Users/DJaap/Library/Python/3.9/bin"

if [[ $(uname -o) = "Darwin" ]] then;
    source ~/.gitlab_creds
    export PYENV_ROOT="$HOME/.pyenv"
    command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi
source ~/.bashrc


# opam configuration
test -r /Users/djaap/.opam/opam-init/init.sh && . /Users/djaap/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true
test -r $HOME/.opam/opam-init/init.sh && . $HOME/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true

# start X11 on linux
#[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx

# Added by Toolbox App
export PATH="$PATH:/Users/DJaap/Library/Application Support/JetBrains/Toolbox/scripts"
