# neovim-bin = "/Users/DJaap/.nix-profile/bin/nvim"
# chdir = "/Users/DJaap/code/gitlab.com/ciorg/church/Reactor/"
neovim-bin = "/home/dillon/.nix-profile/bin/nvim"
chdir = "/home/dillon/code/"

# Font settings - matching kitty
[font]
normal = ["Iosevka Nerd Font Mono"]
size = 12.0
