neovim-bin = "/Users/DJaap/.nix-profile/bin/nvim"
chdir = "/Users/DJaap/code/gitlab.com/ciorg/church/Reactor/"

# Font settings - matching kitty
[font]
normal = ["Iosevka Nerd Font Mono"]
size = 14.0
